### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by oiseauroch**
## Problem

fix weight edition

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by oiseauroch** [comment]
!testme

**Comment by alexAubin** [comment]
(btw not sure why you had to obtain the server's IP (which you actually have no guarantee that it wont change later on x_x) but it seems like it's not used anymore in the .toml ?)

**Comment by oiseauroch** [comment]
It was for the previous version of garage that was not working with dns. Useless now.

**Comment by oiseauroch** [comment]
!testme

**Pull request merged**
