### PR TITLE
You can use less than 3 nodes

### PR DESCRIPTION
**Pull request by lapineige**
Description is wrongly suggesting that you cannot run without 3 nodes
See https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#replication-mode

### CODE REVIEW

**Comment by oiseauroch** [comment]
As you may have seen, I fixed the configuration file for `replication_mode` to 3 and it can't work properly without 3 nodes. 
I prefer to say that it work only with 3 nodes and people that want to go further will be able to make their own tweaks.

**Comment by lapineige** [comment]
But users can change that setting (right ?).
At least they should know it imho.

For my part, I was wrongly mislead for months in believing that Garage was useless for me, before asking Garage devs and get the information (see the documentation link about) that it's not mandatory.
We can still advice for a 3 nodes setup, strongly if needed.

**Comment by lapineige** [comment]
> I fixed the configuration file for replication_mode to 3 

When I set up the replication mode in the config file (https://github.com/YunoHost-Apps/garage_ynh/blob/version-2/conf/garage.toml#L7) to "none" (or 1), and launch garage status, it says :
```
Not enough nodes have an assigned role to maintain enough copies of data.
This new layout cannot yet be applied.
```

Did you force anything in the code ?

**Comment by oiseauroch** [comment]
I didn't change anything in the code. If it's a fresh install, you can try to remove metadata directory

**Comment by lapineige** [comment]
Yes I found that this was the problem afterwards, I forgot to report this. Thanks.

**Comment by lapineige** [comment]
For now it seems to be working, with some clients I can create a file. With other it doesn't work, but I'm unsure what's the root cause here (packaging issue, garage issue, 1 node setup issue, ISP issue…).

**Comment by lapineige** [comment]
Closing in favor of #23

**Pull request closed without merging**
